# Generated by Django 5.2.5 on 2026-03-17 14:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(choices=[('architect', 'Архитектор'), ('lead_architect', 'Ведущий архитектор'), ('designer', 'Дизайнер'), ('constructor', 'Конструктор'), ('manager', 'Менеджер'), ('intern', 'Стажёр')], max_length=50, verbose_name='Должность')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Оклад (тенге)')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name='Дата найма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма бонуса')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='bureau.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Время прихода')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Время ухода')),
                ('check_in_photo', models.ImageField(blank=True, null=True, upload_to='attendance_photos/', verbose_name='Фото при приходе')),
                ('status', models.CharField(choices=[('present', 'На месте'), ('late', 'Опоздание'), ('left', 'Ушла'), ('absent', 'Отсутствует')], default='absent', max_length=20, verbose_name='Статус')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='Опоздание (минут)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='bureau.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_type', models.CharField(choices=[('late_under_30', 'Опоздание до 30 мин'), ('late_over_30', 'Опоздание более 30 мин'), ('absence', 'Прогул без уважительной причины'), ('deadline_3', 'Просрочка дедлайна (до 3 дней)'), ('deadline_7', 'Просрочка дедлайна (3–7 дней)'), ('deadline_more', 'Просрочка дедлайна (более 7 дней)'), ('bad_quality', 'Некачественная сдача работы'), ('manual', 'Ручной штраф')], max_length=30, verbose_name='Тип штрафа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма (тенге)')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='bureau.attendance', verbose_name='Запись посещаемости')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='bureau.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс (%)')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('review', 'На проверке'), ('completed', 'Завершён')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('stage', models.CharField(choices=[('sketch', 'Эскиз'), ('drawing', 'Чертёж'), ('approval', 'Согласование'), ('working_project', 'Рабочий проект'), ('ganplan', 'Генплан'), ('handover', 'Сдан')], default='sketch', max_length=30, verbose_name='Этап')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='bureau.employee', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['deadline'],
            },
        ),
    ]
